### ISSUE TITLE
Invalid Service: mailhog (might have een 

### ISSUE THREAD

**Issue by vorban** [NiclasvanEyk/initializer-for-laravel#248]
**Describe The Bug**
> Invalid services [mailhog].

Looking at laravel docs, it seems like [mailhog has been changed for mailpit](https://laravel.com/docs/9.x/installation#choosing-your-sail-services).

**Chosen Packages & Configuration**
https://laravel.initializer.dev/?preset&vendor=me&php=8.2&starter=laravel&database=mariadb&cache=redis&queue=redis&mail=mailgun&uses-fortify&uses-dbal&uses-mailhog&uses-telescope&uses-pest
1. Laravel Starter
2. MariaDB Database
3. Redis Cache
4. Redis Queue
5. Mailgun Driver
6. Fortify auth
7. DBAL
8. Mailhog
9. Telescope
10. Pest

**Command Line Output**
```
Invalid services [mailhog].
```
Followed by "It looks like something went wrong [...] create an issue".

**Proposed fix**

Replace Mailhog by Mailpit.

**Comment by NiclasvanEyk** [comment]
Thank you so much for reporting this! Apparently it was changed [two days ago](https://github.com/laravel/sail/releases/tag/v1.19.0) in https://github.com/laravel/sail/pull/533.

I changed some of the affected parts of the code, so that everything should work again (did a quick test install and everything worked). Proper refactorings will follow later.
